# ${title}

> Generated by the movie subsystem. Edit frontmatter curation fields and the user notes section only.

## Metadata

- Canonical ID: `${canonical_id}`
- IMDb: `${imdb_id_display}`
- TMDb: `${tmdb_id_display}`
- Year: `${year_display}`
- Collection: `${collection_display}`
- Match Status: `${match_status}`
- Review Required: `${review_required}`

## Provenance

${provenance_bullets}

## Quality

- Apple: `${quality_apple_display}`
- NAS: `${quality_nas_display}`

## Classification

- Duplicate Group: `${duplicate_group}`
- Version Notes: `${version_notes_display}`
- Top 250: `${top_250_display}`

## Credits

- Directors: `${directors_display}`
- Cast: `${cast_display}`
- Genres: `${genres_display}`
- Runtime: `${runtime_display}`
- IMDb Rating: `${imdb_rating_display}`

<!-- MOVIE-USER-NOTES-START -->
## Personal Notes

${user_notes}
<!-- MOVIE-USER-NOTES-END -->
